packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tailwindcss/postcss": ^4.1.13
  "@tanstack/react-query": ^5.85.5
  "@types/node": ^24.9.1
  dotenv-cli: ^8.0.0
  eslint: ^9.34.0
  next-themes: ^0.4.6
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  tailwindcss: ^4.1.13
  typescript: ^5.9.3
  typescript-eslint: ^8.42.0
  zod: ^3.25.67

catalogs:
  react19:
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
    react: 19.2.3
    react-dom: 19.2.3

onlyBuiltDependencies:
  - esbuild

overrides:
  "@types/minimatch": 5.1.2

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
