import type { Place } from "./types";

export const mockPlaces: Place[] = [
  {
    id: "1",
    name: "Plaza de Armas",
    type: "landmark",
    location: {
      lat: -13.5165,
      lng: -71.9787,
    },
    address: "Portal de Panes 123, Cusco",
    description:
      "The historic main square of Cusco, surrounded by colonial arcades and the magnificent Cusco Cathedral. A UNESCO World Heritage site and the heart of the ancient Inca capital.",
    rating: 4.8,
    openingHours: "Open 24 hours",
    checkInRadius: 100,
    points: 50,
    nftReward: true,
    image: "/stylized-illustration-of-cusco-peru-historic-plaza.jpg",
  },
  {
    id: "2",
    name: "Qorikancha Temple",
    type: "museum",
    location: {
      lat: -13.5187,
      lng: -71.9751,
    },
    address: "Plazoleta Santo Domingo, Cusco",
    description:
      "The Temple of the Sun, once the most important temple in the Inca Empire. Its walls were covered in gold, and it housed the mummies of previous Inca rulers.",
    rating: 4.7,
    openingHours: "8:00 AM - 5:30 PM",
    checkInRadius: 80,
    points: 75,
    nftReward: true,
    image: "/flat-vector-illustration-of-machu-picchu-peru-with.jpg",
  },
  {
    id: "3",
    name: "Chicha por Gastón Acurio",
    type: "restaurant",
    location: {
      lat: -13.5147,
      lng: -71.9812,
    },
    address: "Plaza Regocijo 261, Cusco",
    description:
      "Contemporary Peruvian cuisine by renowned chef Gastón Acurio. Experience traditional flavors with a modern twist in a beautiful colonial setting.",
    rating: 4.6,
    openingHours: "12:00 PM - 11:00 PM",
    checkInRadius: 50,
    points: 30,
    nftReward: false,
    image: "/peruvian-cuisine-dining-authentic-food.jpg",
  },
  {
    id: "4",
    name: "Belmond Hotel Monasterio",
    type: "hotel",
    location: {
      lat: -13.5172,
      lng: -71.9794,
    },
    address: "Calle Palacio 136, Cusco",
    description:
      "A luxury hotel set in a 16th-century monastery. Features beautiful courtyards, colonial architecture, and world-class amenities.",
    rating: 4.9,
    openingHours: "Open 24 hours",
    checkInRadius: 60,
    points: 40,
    nftReward: false,
    image: "/andean-lodge-mountain-accommodation-peru.jpg",
  },
  {
    id: "5",
    name: "San Pedro Market",
    type: "business",
    location: {
      lat: -13.5197,
      lng: -71.9842,
    },
    address: "Calle Santa Clara, Cusco",
    description:
      "The largest and most vibrant market in Cusco. Find fresh produce, local crafts, traditional foods, and experience authentic Peruvian culture.",
    rating: 4.5,
    openingHours: "6:00 AM - 6:00 PM",
    checkInRadius: 70,
    points: 25,
    nftReward: false,
  },
  {
    id: "6",
    name: "Sacsayhuamán",
    type: "landmark",
    location: {
      lat: -13.5088,
      lng: -71.9816,
    },
    address: "Sacsayhuamán, Cusco",
    description:
      "Impressive Inca fortress with massive stone walls. The precision of the stonework is remarkable, with some stones weighing over 100 tons.",
    rating: 4.8,
    openingHours: "7:00 AM - 6:00 PM",
    checkInRadius: 150,
    points: 100,
    nftReward: true,
    image: "/flat-vector-illustration-of-nazca-lines-peru-deser.jpg",
  },
  {
    id: "7",
    name: "Museo Inka",
    type: "museum",
    location: {
      lat: -13.5156,
      lng: -71.9801,
    },
    address: "Cuesta del Almirante 103, Cusco",
    description:
      "Comprehensive museum showcasing Inca artifacts, textiles, ceramics, and mummies. Learn about the rich history and culture of the Inca civilization.",
    rating: 4.6,
    openingHours: "8:00 AM - 7:00 PM",
    checkInRadius: 60,
    points: 60,
    nftReward: true,
  },
  {
    id: "8",
    name: "Limo Cocina Peruana",
    type: "restaurant",
    location: {
      lat: -13.5163,
      lng: -71.9789,
    },
    address: "Portal de Carnes 236, Cusco",
    description:
      "Upscale restaurant offering innovative Peruvian-Japanese fusion cuisine with stunning views of Plaza de Armas.",
    rating: 4.7,
    openingHours: "11:00 AM - 11:00 PM",
    checkInRadius: 50,
    points: 35,
    nftReward: false,
  },
  {
    id: "9",
    name: "Centro Artesanal Cusco",
    type: "business",
    location: {
      lat: -13.5142,
      lng: -71.9823,
    },
    address: "Av. El Sol 603, Cusco",
    description:
      "Artisan market featuring high-quality handmade crafts, textiles, jewelry, and souvenirs from local Peruvian artisans.",
    rating: 4.4,
    openingHours: "9:00 AM - 8:00 PM",
    checkInRadius: 60,
    points: 20,
    nftReward: false,
  },
  {
    id: "10",
    name: "Twelve-Angled Stone",
    type: "landmark",
    location: {
      lat: -13.5161,
      lng: -71.9803,
    },
    address: "Hatun Rumiyoc, Cusco",
    description:
      "Famous Inca stone with twelve angles, showcasing the incredible precision of Inca masonry. A popular photo spot and testament to Inca engineering.",
    rating: 4.5,
    openingHours: "Open 24 hours",
    checkInRadius: 40,
    points: 40,
    nftReward: false,
  },
];
